FROM node:20-bookworm-slim
RUN apt-get update -qq && apt-get install -yqq python3 python3-venv curl ca-certificates && \
    curl -LsSf https://astral.sh/uv/install.sh | sh && \
    npm install -g wrangler@4.80.0
ENV PATH="/root/.local/bin:$PATH"
WORKDIR /app
COPY pyproject.toml .
RUN uv sync
COPY . .
CMD ["uv", "run", "pywrangler", "deploy"]
